- name: Clone tfenv repository
  ansible.builtin.git:
    repo: 'https://github.com/tfutils/tfenv.git'
    dest: '/opt/tfenv'
  tags:
    - terraform

- name: Install specified Terraform version
  ansible.builtin.command: /opt/tfenv/bin/tfenv install {{ terraform_version }}
  args:
    creates: '/opt/tfenv/bin/tfenv/versions/{{ terraform_version }}'
  tags:
    - terraform

- name: Use specified Terraform version
  ansible.builtin.command: /opt/tfenv/bin/tfenv use {{ terraform_version }}
  args:
    creates: '{{ ansible_env.HOME }}/.tfenv/version'
  tags:
    - terraform